name: Build and test Kernel Module

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository (owner/repo)
        required: true
        default: RolandoMagico/linux

      ref:
        description: Branch or Commit
        required: true
        default: D-Link-ODM

      module_config:
        description: CONFIG of the module (without CONFIG_)
        required: true
        default: NVMEM_LAYOUT_DLINK_ODM_TLV

      test_config:
        description: CONFIG of the KUnit tests (without CONFIG_)
        required: true
        default: NVMEM_LAYOUT_DLINK_ODM_TLV_KUNIT_TEST
      linux_path:
        description: Path to the linux kernel sources
        required: true
        default: linux

jobs:
  execute:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout Kernel Sources
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: ${{ inputs.linux_path }}
      - name: Update APT
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential gcc make bc flex bison libelf-dev libssl-dev qemu-system-x86 python3

      - name: Create default config
        run: make -C ${{ inputs.linux_path }} defconfig

      - name: Extend default config
        run: cd ${{ inputs.linux_path }} && ./scripts/kconfig/merge_config.sh .config ../defaultconfig

      - name: Build Kernel
        run: make -C ${{ inputs.linux_path }} -j$(nproc)

      - name: Run Tests
        run: cd ${{ inputs.linux_path }} && ./tools/testing/kunit/kunit.py run
