name: Build and test Kernel Module

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository (owner/repo)
        required: true
        default: RolandoMagico/linux

      ref:
        description: Branch or Commit
        required: true
        default: D-Link-ODM

      module_config:
        description: CONFIG of the module (without CONFIG_)
        required: true
        default: NVMEM_LAYOUT_DLINK_ODM_TLV

      test_config:
        description: CONFIG of the KUnit tests (without CONFIG_)
        required: true
        default: NVMEM_LAYOUT_DLINK_ODM_TLV_KUNIT_TEST

jobs:
  execute:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - name: Update APT
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential gcc make bc flex bison libelf-dev libssl-dev qemu-system-x86 python3

      - name: Create default config
        run: make defconfig

      - name: Extend default config
        run: ./scripts/config --enable OF --enable NVMEM_LAYOUTS --enable ${{ inputs.module_config }}

      - name: Build NVMEM
        run: make drivers/nvmem/layouts

      - name: Extend default config for testing
        run: ./scripts/config --enable KUNIT --disable KUNIT_ALL_TESTS --enable ${{ inputs.test_config }}
        
      - name: Run Tests
        run: ./tools/testing/kunit/punit.py run
